iaas-configuration:
  subscription_id: ${subscription_id}
  tenant_id: ${tenant_id}
  client_id: ${client_id}
  client_secret: ${client_secret}
  resource_group_name: ${resource_group_name}
  bosh_storage_account_name: ${bosh_storage_account_name}
  ssh_public_key: "${ssh_public_key}"
  ssh_private_key: "${ssh_private_key}"
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: management
    subnets:
${management_subnets}
  - name: pas
    subnets:
${pas_subnets}
  - name: services
    subnets:
${services_subnets}