network-assignment:
  network:
    name: management
  other_availability_zones: []
  singleton_availability_zone:
    name: ${az}
director-configuration:
  ntp_servers_string: time.google.com
${provided_configuration}
  retry_bosh_deploys: true
  resurrector_enabled: true