product-name: p-redis
product-properties:
  .properties.syslog_selector:
    value: 'No'
  .properties.small_plan_selector.active.az_multi_select:
    value:
    - ${az1}
  .properties.medium_plan_selector.active.az_multi_select:
    value:
    - ${az1}
  .properties.large_plan_selector.active.az_multi_select:
    value:
    - ${az1}
network-properties:
  network:
    name: pas
  service_network:
    name: services
  other_availability_zones:
  - name: ${az1}
  - name: ${az2}
  - name: ${az3}
  singleton_availability_zone:
    name: ${az1}