product-name: p-spring-cloud-services
product-properties:
  .deploy-service-broker.persistence_store_service:
    value: p.mysql
  .deploy-service-broker.persistence_store_service_plan:
    value: db-small
  .deploy-service-broker.message_bus_service:
    value: p.rabbitmq
  .deploy-service-broker.message_bus_service_plan:
    value: single-node-3.7
network-properties:
  network:
    name: pas
  other_availability_zones:
  - name: ${az1}
  - name: ${az2}
  - name: ${az3}
  singleton_availability_zone:
    name: ${az1}
errand-config:
  run-smoke-tests:
    post-deploy-state: false
    pre-delete-state: default