az-configuration:
- name: ${az1}
- name: ${az2}
- name: ${az3}
iaas-configuration:
  access_key_id: ${access_key_id}
  secret_access_key: ${secret_access_key}
  vpc_id: ${vpc_id}
  security_group: ${security_group}
  key_pair_name: ${key_pair_name}
  ssh_private_key: "${ssh_private_key}"
  region: ${region}
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: management
    subnets:
${management_subnets}
  - name: pas
    subnets:
${pas_subnets}
  - name: services
    subnets:
${services_subnets}