version: 0.2

phases:
  install:
    commands:
      - . $CODEBUILD_SRC_DIR/bin/switch.sh
      - . $CODEBUILD_SRC_DIR/bin/install.sh
  build:
    commands:
      - . $CODEBUILD_SRC_DIR/bin/build.sh
  post_build:
    commands:
      - aws s3 cp $HOME/state s3://$state_bucket --recursive