version: 0.2

phases:
  install:
    commands:
      - . $CODEBUILD_SRC_DIR/bin/switch.sh
      - . $CODEBUILD_SRC_DIR/bin/install.sh
  build:
    commands:
      - . $CODEBUILD_SRC_DIR/bin/destroy.sh
      - aws s3 rm s3://$state_bucket --recursive
  post_build:
    commands:
      - echo 'None'