version: 0.2

phases:
  install:
    commands:
      - . $CODEBUILD_SRC_DIR/bin/install.sh
  build:
    commands:
      - . $CODEBUILD_SRC_DIR/bin/build.sh
      - aws s3 rm s3://$env.$region.$account.paasify-state --recursive
  post_build:
    commands:
      - echo 'None'
